version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
  
  goon-files:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongo
    ports:
      - 8000:80
    environment:
      DB_MONGO_HOST: mongo
      DB_MONGO_PORT: 27017
      DB_MONGO_USER: root
      DB_MONGO_PASS: password
      DB_MONGO_DB_NAME: goon-files